### PR TITLE
Enable task api invocation and set host default to be empty

### PR DESCRIPTION
**Pull request by qiuminwei**

### CODE REVIEW

**Comment by kunal-pmj** [comment]
Hi @qiuminwei 

removing <vcenter> from the host would reintroduce following [issue](https://github.com/vmware/vmware-openapi-generator/issues/4) which was addressed by [this ](https://github.com/vmware/vmware-openapi-generator/pull/5) pull request.

We would need a solution which addressed both, older and new problem.

**Comment by qiuminwei** [comment]
Hi @kunal-pmj 

How about extracting host as input parameter?

**Comment by kunal-pmj** [comment]
> Hi @kunal-pmj
> 
> How about extracting host as input parameter?

You mean using the input parameter 'vc' as host? 

That way the generated doc will carry VC hostname/Ip. 

@jrgarcia  can you provide inputs on this?

Thanks
Kunal

**Comment by qiuminwei** [comment]
No, I mean adding a new parameter ‘--host’, I sent a [review ](https://reviewboard.eng.vmware.com/r/1530096/)before but canceled it.

By the new input parameter you can replace the host with the real hostname/IP, or use the default value( `<vcenter>`) if you just want to generate the document.

**Comment by kunal-pmj** [comment]
> No, I mean adding a new parameter ‘--host’, I sent a [review ](https://reviewboard.eng.vmware.com/r/1530096/)before but canceled it.
> 
> By the new input parameter you can replace the host with the real hostname/IP, or use the default value( `<vcenter>`) if you just want to generate the document.

Kindly add the parameter.

**Comment by jrgarcia** [comment]
I would be ok with adding another parameter to pass in host information. The thing I was trying to avoid by using `<vcenter>` was generating a binding from this that sets a host that no one could reach. I thought about using `vcenter.example.com` and then `localhost`, but I wanted a default that would fail fast (`<vcenter>` isn't valid) and wouldn't lead users to believe that there was a public host available.

**Pull request closed without merging**
