### PR TITLE
Changes to replace . with _ in the model reference

### PR DESCRIPTION
**Pull request by kunal-pmj**
Signed-off-by: Kunal Singh<singhk@vmware.com>

### CODE REVIEW

**Comment by kunal-pmj** [comment]
This will fix following issue : https://github.com/vmware/vmware-openapi-generator/issues/50

**Comment by sreeshas** [comment]
Is "_" the preferred option always? How would this change affect other languages?

**Comment by kunal-pmj** [comment]
Some generators like java and Python handle "." by replacing it with _ or CamelCasing it.

**Comment by sreeshas** [comment]
So replacing . with _ might break those generators. 
Ideally generators should not influence spec. 
If majority of generators are okay with ".", we should leave it as it is.  typescript generator can add the functionality to replace "." to whatever is reasonable.

**Pull request closed without merging**
